succinctlabs/sp1

core/src/syscall/precompiles/sha256/compress/mod.rs, core/src/syscall/precompiles/sha256/compress/trace.rs, sha_compress_test.sh
https://github.com/succinctlabs/sp1/pull/216 introduces a range check for `Add5Operation`.
Sha compress doesn't call `eval` though it calls `populate`. This causes an interaction bug. 
It is a TODO item that we need to call `eval`, and we're trying to get it to asap. this is a temporary fix.
=> fix: sha compress

book/getting-started/install.md
Fix issue https://github.com/succinctlabs/sp1/issues/256, with @puma314 and @ctian1 's help.
> Uma: the reason it's complaining is that it's trying to clone the Rust monorepo inside of sp1 and then it gets mad that the sp1 Cargo.toml doesn't have the rust subdirectory as a workspace.
So just do it in a fully clean folder that isn't a rust workspace (like your home directory or documents directory)
=> fix: wrong workspace building error

core/src/io.rs, core/src/lib.rs
Previously, the type `Proof` implemented a custom serializer which hex encoded the proof data but did *not* implement a corresponding deserializer. This caused roundtrip deserialization to fail. 
This PR makes two improvements. First, it adds a custom deserializer for the `Proof` type. Second, it adds `hex` encoding only when the target serialization format is human-readable - eliminating overhead in binary formats. This PR also adds tests on roundtrip encoding for the `SP1ProofWithIO` type, which contains `Proof`. 
Fixes #247
=> fix: debug deserialization for SP1ProofWithIO. Test.

book/getting-started/quickstart.md, cli/src/assets/program/main.rs, cli/src/assets/script/main.rs
In issue #244 I noted that the current quickstart has a small issue regarding integer overflow in the fibonacci example. This PR addresses the issue by changing the program to use `u128` in order to generate larger numbers without overflow, and also notes the limitations of the implementation in a comment and the quickstart.
=> fix: edit fibonacci example to use `u128` and note overflow case in quickstart

Cargo.lock, examples/chess/program/Cargo.lock, examples/ed25519/program/Cargo.lock, examples/fibonacci-io/program/Cargo.lock, examples/fibonacci/program/Cargo.lock, examples/json/program/Cargo.lock, examples/regex/program/Cargo.lock, examples/rsa/program/Cargo.lock, examples/ssz-withdrawals/program/Cargo.lock, examples/tendermint/program/Cargo.lock, tests/blake3-compress/Cargo.lock, tests/cycle-tracker/Cargo.lock, tests/ecrecover/Cargo.lock, tests/ed-add/Cargo.lock, tests/ed-decompress/Cargo.lock, tests/keccak-permute/Cargo.lock, tests/keccak256/Cargo.lock, tests/secp256k1-add/Cargo.lock, tests/secp256k1-decompress/Cargo.lock, tests/secp256k1-double/Cargo.lock, tests/sha-compress/Cargo.lock, tests/sha-extend/Cargo.lock, tests/sha2/Cargo.lock, zkvm/entrypoint/Cargo.toml, zkvm/entrypoint/src/lib.rs, zkvm/entrypoint/src/libm.rs
fixes "rust-lld" errors when using packages like statrs or bigint by adding math instrinsics from rust-lang/libm
in the future it might be possible to fix this in rust / compiler-builtins like for wasm: https://github.com/rust-lang/compiler-builtins/pull/248
=> fix(zkvm): libm math intrinsics

core/src/air/builder.rs, core/src/alu/divrem/mod.rs, core/src/alu/divrem/utils.rs, core/src/cpu/air/memory.rs, core/src/cpu/air/mod.rs, core/src/syscall/precompiles/edwards/ed_decompress.rs
No functional changes, just light refactoring.
=> refactor: various AIR tweaks

core/src/utils/prove.rs
x^5 works with Mersenne31, but x^7 is the smallest permutation monomial over BabyBear. I think this mistake originates in some Plonky3 example code which had the same issue.
=> fix: S-box in Poseidon2 config

.github/workflows/docker-publish.yml, book/getting-started/install.md, cli/docker/Dockerfile, cli/src/build.rs
Sets up the same behavior for docker as [Foundry](https://book.getfoundry.sh/getting-started/installation?highlight=docker#using-foundry-with-docker) has, with the same CI for pushing `nightly`, `latest`, and `v*.*.*` images to GHCR.
To test, try:
```
docker pull ghcr.io/succinctlabs/sp1:latest
```
=> feat: add instructions for docker usage and setup CI

book/writing-programs/cycle-tracking.md
The book currently instructs users to set RUST_LOG to 'info' for the cycle-tracker. However, in #363, the log level for the cycle-tracker was changed to 'debug'. 
This Pull Request updates the RUST_LOG level in the book from 'info' to 'debug', matching the actual setting in the code. This ensures that users following the book's instructions will see the expected logs.
=> fix: RUST_LOG log level in cycle-tracking section of book

Cargo.lock, examples/fibonacci-io/script/Cargo.lock, sdk/Cargo.toml, sdk/src/client.rs
Removes `rmp-serde` usage in favor of bincode everywhere
=> fix: use bincode for sdk serialization

sdk/src/lib.rs
Instead of directly choosing to remote prove off of `PRIVATE_KEY`, check for `REMOTE_PROVING=true`.
=> fix: use REMOTE_PROVE to check local or remote

sdk/src/lib.rs
Execute before `prove_remote_async` in the SDK. If a user attempts to request a proof with a failing runtime, it will be caught at this point.
=> feat: execute before `prove_remote_async`

helper/src/lib.rs
Some break changes happened a few days ago. Like the `syscall code` changed: 
https://github.com/succinctlabs/sp1/commit/bde25d674d2f06acde6999ef5b507f44b6aa5fcd
```diff
-HALT = 0x01_00_00_00,
+HALT = 0x00_00_00_00,
```
So, when I update the dependency of SP1 to the newest one. Undefined Behavior happened.
```shell
panic: invalid syscall number: 1
```
This is usually because sp1 has encountered an unsupported instruction, but my program was compiled by the same version of SP1 with a rust build script. So, the mistakes happened in the script. When I was deep into the implementation. I found the misused of `cargo::rerun-if-changed` and the examples of SP1 always `cargo clean&&cargo build`manually. Therefore, there won't be any issues with examples. …
=> fix: rerun failed in build script

sp1up/sp1up
...per title. 
Currently any commands to install versions of sp1 via specific commits, it errors thusly: 
```bash
user@archlinux:~/sp1|⇒ sp1up --commit 72cb1bac
.______  ._______ ._______ ._______ ._______ ._______ ._______ ._______ ._______
_____  ____  ___
/ ___/ / __ \<  /
\__ \ / /_/ // /                        A performant, 100% open-source,
___/ // ____// /                              general-purpose zkVM.
/____//_/    /_/
._______ ._______ ._______ ._______ ._______ ._______ ._______ ._______ ._______
Repo       : https://github.com/succinctlabs/sp1
Book       : https://succinctlabs.github.io/sp1
Telegram   : https://t.me/succinct_sp1
._______ ._______ ._______ ._______ ._______ ._______ ._______ ._______ ._______
Cloning into 'sp1'...
remote: Enumerating objects: 22185, done. …
```
=> fix(sp1up): <- make that use `main` branch instead of `master`

cli/src/build.rs
Subcommands like build allow ignoring the minimum rust version of dependencies by the --ignore-rust-version flag. Given that Sp1 locks on certain rustc version while the dependencies of zkvm guest code might often require a higher version, we should allow users to optimistically compile guests without this check.
Inspired by: https://github.com/rust-lang/cargo/issues/11718
=> feat: added `--ignore-rust-version` to `cargo prove build`

recursion/core/src/poseidon2/external.rs, recursion/core/src/poseidon2/mod.rs, recursion/core/src/poseidon2_wide/external.rs, recursion/core/src/poseidon2_wide/mod.rs
`Poseidon2Chip` doesn't match plonky3's poseidon2 implementation. In particular:
1. The AIR expresses the initial round as happening _instead of_ the first external round, not [in addition to it](https://github.com/Plonky3/Plonky3/blob/10b6d44d4eb8b604fba633cdc3a84c5c3720749b/poseidon2/src/lib.rs#L172).
2. The `apply_m_4` helper copied from plonky3 no longer matches. I suspect this is because the old version is the matrix used by Horizen Labs in the paper, which plonky3 used to use until plonky3 switched to a more efficient one.
In the course of implementing this PR, I also made the following changes:
- add tests matching the ones in the other poseidon2 chip.
- change the linear layer helpers in `poseidon2_wide/mod.rs` to operating in-place on the state.
=> fix(recursion): poseidon2 chip matches plonky3

core/Cargo.toml
Give more flexibility to libraries (such as `sp1-reth`) when resolving `strum`. Previously, the version of `0.26.2` was causing some dependency conflicts, as some libraries such as `alloy-chains` were locked to `0.26.1`.
=> fix: downgrade `strum`

core/src/utils/prove.rs, eval/src/main.rs, prover/src/lib.rs, prover/src/utils.rs
Move `get_cycles` utility method into `sp1-prover` for use in benchmarking.
=> refactor: `get_cycles`

recursion/circuit/src/lib.rs, recursion/core/src/stark/config.rs
in the circuit, each babybear elemnet is log2(15*2^27+1)*8=247 bits which is less than Bn254, so we can actually absorb 8 elements, not 7 per Bn254. Should increase hashing efficiency at the leaves by ~15%.
=> fix: circuit sponge absorb rate

core/src/air/builder.rs, core/src/air/public_values.rs, core/src/air/word.rs, core/src/operations/fixed_shift_right.rs
Just some low-hanging fruit for now. Some allocations might be harder to avoid; we could also try
- inlining things (if they aren't already) as needed to help the compiler get rid of annotations
- using a user-space allocator like jemalloc, which seems a lot better than macOS system allocator at least
=> refactor: avoid a few allocations in constraint code

.github/workflows/groth16.yml, recursion/gnark-ffi/src/groth16.rs, recursion/gnark/main.go, recursion/gnark/server/load.go, recursion/gnark/server/server.go
Adds:
* parallel loading of r1cs and pk
* pk using WriteRawTo and UnsafeReadFrom
* add more logging + timings for debugging
* CI: https://github.com/succinctlabs/sp1/actions/runs/8900694723/job/24442833596#step:6:659
Example output:
```
Running 'serve' with data=build, type=groth16, version=3
Files found, loading circuit...
Loading artifacts start time 2024-05-01T03:19:27Z
Opening PK file at: build/pk_groth16.bin
Reading PK file...
Opening R1CS file at: build/circuit_groth16.bin
Reading R1CS file...
PK loaded in 3m46.522924354s
R1CS loaded in 4m38.507870276s
Circuit artifacts loaded successfully in 2024-05-01 03:24:06.214061705 +0000 UTC m=+278.514784538
Circuit artifacts loaded successfully
Starting server on 8082
BatchProve 1 1
14:42:22 DBG prover done backend=groth16 curve=bn254 …
```
=> feat: load circuit artifacts in faster

sdk/src/provers/local.rs
Download the Groth16 artifacts only when `prove_groth16` is called on the `LocalProver`.
Previously, when users initialize a ProverClient (which default to LocalProver) without any `.env` configuration, it will immediately download the Groth16 artifacts, which is bad UX. Users only need the Groth16 artifacts when they call `prove_groth16`, so we should only download the artifacts/check for the artifacts then.
=> fix: download Groth16 artifacts on `prove_groth16` invocation

.github/workflows/release.yml
makes it so latest tagged release is always pinned on homepage of repo. our releases will always have working groth16 artifacts
=> chore: disable nightly release

book/writing-programs/cycle-tracking.md, core/src/syscall/write.rs
Activate `cycle-tracker` with `RUST_LOG`=`info` rather than `debug`. Update the `book` docs to include these changes.
=> feat: activate `cycle-tracker` with `RUST_LOG=info`

Cargo.lock, core/Cargo.toml, core/src/io.rs
Add `hash_public_values` to `core` to mirror the implementation of `hashPublicValues` in the Solidity verifier. This will be useful in https://github.com/succinctlabs/sp1/pull/729, where we'll add proof verification.
=> feat: add `hash_public_values`

recursion/core/src/poseidon2/external.rs, recursion/core/src/poseidon2_wide/external.rs
This PR addresses this [issue](https://github.com/succinctlabs/sp1/issues/743) that is caused from an incorrect flag for the external round.
It also adds expected failure cases to both the poseidon2 chips.
=> fix(recursion): poseidon2 external flag

Cargo.lock, cli/src/assets/program/Cargo.toml, cli/src/assets/script/Cargo.toml, zkvm/entrypoint/Cargo.toml, zkvm/precompiles/Cargo.toml
CI was breaking on the CLI test due to `get_random` v0.2.15 requiring `libc` ^0.2.154, but 0.2.154 was yanked off of `crates.io`. 
To fix this, I've downgraded the version of `get_random` to v0.2.14 so that `sp1` builds. I've also opened an issue in `getrandom`: https://github.com/rust-random/getrandom/issues/423
Additionally, I temporarily updated the version of SP1 in the dependencies of `cargo prove new` to point to this branch so that CI would pass. We'll need to revert that once the testnet version is released.
=> fix(ci): downgrade `getrandom`

.github/workflows/pr.yml, zkvm/entrypoint/Cargo.toml, zkvm/precompiles/Cargo.toml
`cargo prove new` is currently broken due to https://github.com/rust-random/getrandom/issues/423. This PR downgrades the version of `getrandom` to `v0.2.14`.
=> fix: `getrandom` version

.github/workflows/release.yml, sp1up/sp1up
Install go to fix CI, and point `sp1up` CLI script to `main`.
=> fix: update release workflow

core/benches/main.rs
Compiling with `cargo build --release --all-targets` would otherwise fail with the following: `error: failed to evaluate generic const expression`
=> fix(core): Fix benches warning for unstable features

core/src/alu/sr/mod.rs, core/src/lib.rs
Removes a constraint that asserts nothing in the evaluation of `ShiftRightChip`.
Note that I haven't reviewed the whole associated constraint set, hence do not know if this is a miswritten constraint leading to an under-constrained system or simply a leftover.
=> fix(core): Remove dummy constraint

.github/workflows/eval.yml, .github/workflows/main.yml, .github/workflows/pr.yml
Node16 is deprecated and Actions using it will stop being used 3rd of June
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> chore: upgrade checkout action to version with node20

recursion/gnark-ffi/go/sp1/prove.go, recursion/gnark-ffi/go/sp1/utils.go, sdk/src/lib.rs
Encode the proof into the expected Solidity verifier format using `MarshalSolidity`. Previously, when trying to use the `encoded_proof` from the `PlonkBn254Proof`, we would get the proof bytes were too large, as we were using the `raw_proof`.
Also, removes the `test_prove_e2e` tests as they're redundant given the `test_prove_e2e_plonk` tests.
=> feat: encode proof solidity

book/generating-proofs/network.md, sdk/src/lib.rs
Change `ProverClient::remote()` to `ProverClient::network()`. Change usage of `remote` in docs to `network`.
=> refactor: ProverClient::remote -> ProverClient::network

Cargo.lock, sdk/Cargo.toml, sdk/src/lib.rs, sdk/src/provers/local.rs, sdk/src/provers/mock.rs, sdk/src/provers/mod.rs, sdk/src/provers/network.rs
Change `id` field of the Prover to output `prover_type`.
Uses `strum` to automatically format the `ProverType` enum for formatting.
=> feat: add `prover_type`

.github/workflows/main.yml
Enforce that only `dev` can merge into `main` in a GitHub workflow. This will prevent accidental merges into `main`.
TODO: I'll add this as a required check before merging into `main` once this is merged into `main`.
Example accidental merge: https://github.com/succinctlabs/sp1/pull/840
Source: https://stackoverflow.com/questions/71120146/allowing-only-certain-branches-to-pr-merge-to-mainmaster-branch
=> feat: enforce only `dev` can merge into `main`

recursion/gnark-ffi/build.rs
* gnark-ffi building fails on certain mac versions due to missing macOS frameworks
* not sure exactly what combination of versions or dependencies causes it to happen as it worked before, but linking them fixes the issue
* see https://github.com/golang/go/issues/42459#issuecomment-896089738
fixes #841
=> fix: gnark-ffi linking on mac

core/src/runtime/mod.rs, core/src/runtime/syscall.rs, examples/fibonacci/script/bin/execute.rs, prover/src/lib.rs, sdk/src/lib.rs, sdk/src/provers/mock.rs, sdk/src/provers/mod.rs, sdk/src/provers/network.rs
allows callers can check cycles, also removes cycle check / simulation from proof requests
=> feat: execute() exposes ExecutionReport

core/benches/main.rs, core/src/lib.rs, core/src/syscall/precompiles/weierstrass/weierstrass_add.rs, core/src/syscall/precompiles/weierstrass/weierstrass_decompress.rs, core/src/syscall/precompiles/weierstrass/weierstrass_double.rs, core/src/utils/mod.rs, eval/src/main.rs, prover/scripts/build_plonk_bn254.rs, prover/scripts/e2e.rs, prover/scripts/fibonacci_groth16.rs, prover/scripts/fibonacci_sweep.rs, prover/scripts/tendermint_sweep.rs, prover/src/lib.rs, recursion/core/src/poseidon2_wide/external.rs, recursion/program/src/lib.rs, rust-toolchain, sdk/src/lib.rs
Removes the dependency on generic const expressions.
=> feat: generic const expr

core/src/io.rs
Derive `Default` on `SP1Stdin` and `SP1PublicValues` for external use and remove unnecessary bounds from read/write on SP1Stdin and SP1PublicValues.
=> chore: refactor derive, serialize bounds

book/generating-proofs/basics.md, tests/fibonacci/Cargo.toml
Fixes the below by changing the name of the `fibonacci-program` crate in `tests`.
```
warning: skipping duplicate package `fibonacci-program`
```
=> chore: fix duplicate fibonacci program

zkvm/entrypoint/src/syscalls/bigint.rs, zkvm/entrypoint/src/syscalls/mod.rs, zkvm/precompiles/src/lib.rs, zkvm/precompiles/src/uint256_div.rs
sys_bigint impl should be in sp1-zkvm, not sp1-precompiles. This should fix "duplicate symbol" error when sp1-precompiles is in multiple places in dependency tree
=> fix: sys_bigint duplicate symbol

core/src/utils/options.rs
Reads runtime env vars `SHARD_SIZE` and `SHARD_BATCH_SIZE` into `SP1CoreOpts::default()`. It seems they just weren't applied before.
=> fix: set core opts from SHARD* env vars

zkvm/entrypoint/src/lib.rs
The use of the `jal` instruction fails in the entrypoint when the jump is greater than `2^20` (1MB). 
Solution: One line change to the program to use `call` instead of `jal`, which LLVM can use appropriately.
> `jal` is an RISC-V raw instruction that jumps to `__start`, where __start is represented by a signed 20-bit offset from the pc. This means that it can jump either backward up to 1MB or forward up to 1MB.
Compilation time error when running `cargo prove build` inside of `sovereign-sdk` for a large program:
>   = note: rust-lld: error: /Users/ratankaliani/sovereign/sovereign-sdk-wip/examples/demo-rollup/provers/sp1/guest-mock/target/riscv32im-succinct-zkvm-elf/release/deps/sov_demo_prover_guest_mock_sp1-43efdbec6e025eb5.sov_demo_prover_guest_mock_sp1.e995a60d3b6bb61f-cgu.05.rcgu.o:(.t …
=> fix: replace `jal` with `call` in entrypoint

.github/workflows/docker-publish-gnark.yml, core/src/lib.rs, prover/Makefile, prover/release.sh, prover/src/build.rs, prover/src/install.rs, prover/src/lib.rs, recursion/gnark-ffi/src/ffi/docker.rs, sdk/src/network/prover.rs
* Have global circuit version string rather than plonk commit
* This is easier to track than commit as it directly maps to an sp1-sdk release
=> feat: sp1 circuit version

book/verifying-proofs/solidity-and-evm.md, recursion/gnark-ffi/assets/ISP1Verifier.txt, recursion/gnark-ffi/assets/SP1MockVerifier.txt, recursion/gnark-ffi/assets/SP1Verifier.txt
Reduce the Solidity version required by the SP1 Ethereum contracts to `0.8.19` to match the auto-generated gnark PLONK verifier. This way, users can choose any version >= `0.8.19` to compile with, as the previous verison of `0.8.25` could be too restrictive.
The contracts associated with the next release will automatically update to this version.
=> fix: reduce minimum Solidity version for SP1 contracts

.github/workflows/docker-gnark.yml, .github/workflows/main.yml, .github/workflows/pr.yml
Disable usage of spot instances for `test-x86`, `test-arm` and Plonk native, which were flaky due to spot instance interruption.
=> chore(ci): disable spot for larger ci jobs

core/src/syscall/write.rs
Hook results must be accessed immediately after calling.
One no longer has to rely on the `input_stream` being empty when calling a hook and accessing its results.
=> feat: put hook results in front of the input stream

recursion/core-v2/src/alu.rs, recursion/core-v2/src/lib.rs, recursion/core-v2/src/machine.rs, recursion/core-v2/src/mem.rs
The base field ALU (currently the only ALU) uses `AddressValueBase` to avoid extra columns and checks. Some ugly abstractions remain and need to be fixed.
=> feat: make `AddressValue.value` a `Block`

book/getting-started/install.md, cli/src/commands/install_toolchain.rs
Previous experience installing SP1 if rust not found:
```
Downloaded https://github.com/succinctlabs/rust/releases/download/succinct-v2024-02-24.1/rust-toolchain-aarch64-unknown-linux-gnu.tar.gz to File { fd: 12, path: "/root/.sp1/rust-toolchain-aarch64-unknown-linux-gnu.tar.gz", read: false, write: true }
[00:00:15] [#################################################################] 372.11 MiB/372.11 MiB (23.97 MiB/s, 0s)Error: No such file or directory (os error 2)
sp1up: command failed: /root/.sp1/bin/cargo-prove prove install-toolchain
```
This PR makes it so immediately throws an error if rust isn't installed and prompts user to install it first.
=> feat(cli): check for rust usage during installation

sdk/src/network/auth.rs, sdk/src/network/client.rs
Removes Twirp references:
Previous: 
> called `Result::unwrap()` on an `Err` value: twirp error: TwirpErrorResponse { code: InvalidArgument, msg: "version is invalid, only 'e48c01ec' is supported - use sp1 commit 'e48c01ec' and try again", meta: {"argument": "version"} }
After change:
> called `Result::unwrap()` on an `Err` value: error: "InvalidArgument" message: "version is invalid, only 'e48c01ec' is supported - use sp1 commit 'e48c01ec' and try again"
also removing relay usage.
=> feat: improve network prover error output

.github/workflows/pr.yml, cli/src/commands/new.rs
`cargo prove new --version <version>` will clone the specific version of the template, defaulting to `main` (which from this point forward, will be the latest release version, as we will follow the same release proceedure in the template as we do sp1).
We now have a `dev` branch in template that we can use for CI. If there were any breaking changes in the SDK, CI will fail and we should update the template to match the changes.
=> feat(cli): allow template version and fix CI

recursion/program/src/fri/two_adic_pcs.rs
This change doesn’t seem to impact the logic as `blowup` is used solely to calculate matrix heights through the expression `mat.domain.size() * blowup`, and these computed heights are then only used in equality comparisons against each other. Any nonzero value for blowup should therefore "work". (But this does make me wonder why both `batch_heights_log2` and `batch_dims` are computed, since the former should also work for this kind of logic.)
=> fix: use correct value for blowup

core/src/syscall/precompiles/keccak256/air.rs, core/src/utils/prove.rs, prover/src/lib.rs, recursion/program/src/constraints.rs, recursion/program/src/machine/mod.rs, recursion/program/src/stark.rs
Example output:
```
2024-07-02T21:15:10.518487Z  INFO prove_core: summary: cycles=11106, e2e=2.716364875, khz=4088.55, proofSize=1419784
2024-07-02T21:15:10.523268Z  WARN prove_core: high cycle count, consider using the prover network for proof generation: https://docs.succinct.xyz/prover-network/setup.html
2024-07-02T21:15:10.523282Z  INFO prove_core: close time.busy=2.72s time.idle=27.5µs
```
=> feat: suggest prover network if high cycles

cli/src/build.rs
allows for `cargo prove build --docker --tag v1.0.8-testnet`
=> feat(cli): build --docker accepts an optional image tag

book/getting-started/install.md, cli/src/commands/install_toolchain.rs, cli/src/lib.rs, sp1up/sp1up
During `sp1up` installation, you can run into this:
```
Successfully cleaned up ~/.sp1 directory.
Successfully created ~/.sp1 directory.
thread 'main' panicked at cli/src/lib.rs:72:41:
Failed to download Succinct toolchain. Likely caused by GitHub rate limiting. Please try again.
```
Now you can use `sp1up --token $GITHUB_TOKEN` to avoid the rate-limiting.
=> feat(cli): use GH token during installation to avoid rate limiting

.github/dependabot.yml, Cargo.lock, sdk/Cargo.toml
Twirp requires axum `0.7.4`
```
error: failed to select a version for `axum`.
... required by package `twirp v0.3.0 (https://github.com/github/twirp-rs.git?rev=c85f31f9c54957374e7dcb3534fc52cff0aa2dc5#c85f31f9)`
... which satisfies git dependency `twirp` of package `sp1-sdk v0.1.0 (https://github.com/succinctlabs/sp1.git?tag=v1.0.4-testnet#2ce75c6e)`
... which satisfies git dependency `sp1-sdk` of package `zkdna-script v0.1.0 (/Users/zachobront/code/zkdna/script)`
versions that meet the requirements `^0.7` (locked to 0.7.4) are: 0.7.4
all possible versions conflict with previously selected packages.
previously selected package `axum v0.7.5`
... which satisfies dependency `axum = "=0.7.5"` of package `sp1-sdk v0.1.0 (https://github.com/succinctlabs/sp1.git?tag=v1.0.4-testnet#2ce75c6e)`
... …
```
=> fix(sdk): lock axum to 0.7.4

book/what-is-a-zkvm.md, book/writing-programs/patched-crates.md, book/writing-programs/setup.md
`[writing programs](../writing-programs/setup.md)` doesn't lead anywhere
=> docs: fix broken link to setup

.github/workflows/main.yml
When merging dev into main, run some examples:
=> ci: run examples on merge to main

zkvm/lib/src/utils.rs
fixes https://github.com/succinctlabs/sp1/issues/1024
=> fix: handle mul_assign scalar zero

book/developers/common-issues.md
Add two common issues to the documentation:
- Importing a package with an MSRV > the Succinct Rust toolchain.
- Stack Overflow errors when running in `debug` mode.
=> docs: add common issues

prover/src/lib.rs, prover/src/types.rs, recursion/circuit/src/constraints.rs, recursion/compiler/examples/fibonacci.rs, recursion/compiler/src/ir/utils.rs, recursion/compiler/tests/arithmetic.rs, recursion/compiler/tests/array.rs, recursion/compiler/tests/conditionals.rs, recursion/compiler/tests/for_loops.rs, recursion/compiler/tests/io.rs, recursion/compiler/tests/lt.rs, recursion/compiler/tests/poseidon2.rs, recursion/compiler/tests/public_values.rs, recursion/core/src/runtime/mod.rs, recursion/core/src/stark/utils.rs, recursion/program/src/stark.rs
bubble up `SP1RecursionProverError` instead of exit(1)
=> feat: result instead of exit(1) on trap in recursion

Cargo.lock, prover/src/lib.rs, sdk/src/lib.rs
Export the ExecutionReport for external usage from the SDK.
=> chore: export execution report

cli/src/commands/config-ci.toml, cli/src/commands/config.toml
fixes this error: 
> Building bootstrap
> failed to parse TOML configuration 'config.toml': unknown field `changelog-seen`
=> fix: remove changelog-seen from config.toml

Cargo.lock, core/Cargo.toml, core/src/cpu/columns/opcode_specific.rs, recursion/core/src/cpu/columns/opcode_specific.rs
The following test previously caused undefined behavior in `sp1-recursion-core`, as can be seen by running with [Miri](https://github.com/rust-lang/miri).
```rust
#[cfg(test)]
mod tests {
use crate::cpu::columns::opcode_specific::OpcodeSpecificCols;
#[test]
fn test_ub() {
let cols: OpcodeSpecificCols<usize> = Default::default();
dbg!(cols);
}
}
```
```
cargo miri test -p sp1-recursion-core cpu::columns::opcode_specific::tests::test_ub
```
The problem is that the `Default` implementation previously relied on the `Default` implementation of a field smaller than the union itself. Rust pads any such field to match the size of the union, causing UB when these uninitialized padding bytes are transmuted to an array.
I added the `static_assertions` dependency to `sp1-core` to match …
=> fix: UB from `OpcodeSpecificCols` union

core/src/syscall/write.rs
In a previous PR (https://github.com/succinctlabs/sp1/pull/707), forgot to emit the function name `info` instead of `debug`, resulting in behavior which did not match the specified behavior: https://docs.succinct.xyz/writing-programs/cycle-tracking.html. 
In the future, we should use a specific module target so that users aren't seeing generic RUST_LOG statements from underlying libraries when using SP1.
=> fix: cycle tracking logs

book/writing-programs/patched-crates.md
The existing patches for `reth` and `revm` are not maintained, and users have run into issues using them. We should remove them from the officially supported patched crates list until they are fully supported.
We can re-add these patches once https://github.com/succinctlabs/rsp is complete, and the corresponding patches are finalized.
=> docs: remove `reth`, `revm` patches

book/onchain-verification/solidity-sdk.md
how to use different solidity version if not using 8.20.0
=> docs: using different solidity versions

zkvm/entrypoint/src/syscalls/halt.rs
context:
```
[sp1]  warning: creating a mutable reference to mutable static is discouraged
[sp1]    --> /Users/mattstam/go/src/github.com/succinctlabs/sp1/zkvm/entrypoint/src/syscalls/halt.rs:25:47
[sp1]     |
[sp1]  25 |         let pv_digest_bytes = core::mem::take(&mut zkvm::PUBLIC_VALUES_HASHER)
[sp1]     |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
[sp1]     |
[sp1]     = note: for more information, see issue #114447 <https://github.com/rust-lang/rust/issues/114447>
[sp1]     = note: this will be a hard error in the 2024 edition
[sp1]     = note: this mutable reference has lifetime `'static`, but if the static gets accessed (read or written) by any other means, or any other reference is created, then any further …
```
=> fix: mutable static ref warning in halt syscall

book/writing-programs/patched-crates.md
- Add specific documentation for `Ed25519` and `secp256k1` acceleration.
- Add new supported crates.
- Update method for verifying syscalls.
=> docs: patched crate documentation

cli/docker/Dockerfile
need `xz-utils` to decompress the .tar.xz file containing the RISC-V toolchain
=> fix: docker build xz-utils

cli/src/commands/new.rs
=> feat: `cargo prove new` cloning message

build/src/lib.rs, helper/src/lib.rs
The original path of the ELF when the `binary` flag is supplied was incorrect. The binary file name matches the `binary` flag, or it is the package's name.
Discovered while testing https://github.com/succinctlabs/sp1/pull/1276
=> fix: Copy `sp1-helper` binary build

book/developers/common-issues.md
Add documentation for common issues with `syscall_verify_sp1_proof` and update the docs for `ignore-rust-version`.
=> docs: common issues for `syscall_verify_sp1_proof` and `ignore-rust-version`

zkvm/lib/src/lib.rs, zkvm/lib/src/verify.rs
Correct the naming for the inputs to `verify_sp1_proof` and make them consistent.
=> chore: `verify_sp1_proof` naming

Cargo.lock, recursion/circuit-v2/src/utils.rs, recursion/compiler/Cargo.toml, recursion/compiler/src/circuit/compiler.rs, recursion/compiler/src/circuit/mod.rs, recursion/core-v2/src/chips/mem/constant.rs, recursion/core-v2/src/chips/poseidon2_skinny/mod.rs, recursion/core-v2/src/chips/poseidon2_wide/mod.rs, recursion/core-v2/src/lib.rs, recursion/core-v2/src/machine.rs, recursion/core-v2/src/runtime/instruction.rs, recursion/core-v2/src/runtime/mod.rs
- Employ fusion (avoid building intermediate data structures) in the compiler.
- Clone the program one less time in `Runtime::new`.
- Shrink the `Instruction` enum by boxing the particularly large `CommitPublicValues` variant.
- Replace the `HashMap` used for runtime memory by a `Vec`.
=> perf: various optimizations in v2 compiler/runtime

crates/cli/Cargo.toml, crates/cli/README.md, crates/cli/src/bin/cargo-prove.rs, crates/cli/src/commands/mod.rs, crates/cli/src/commands/vkey.rs
```sh
cargo prove vkey --elf examples/tendermint/program/elf/riscv32im-succinct-zkvm-elf
Verification Key Hash:
0x00c8cf1fbd86e856e8cb5b1dabfff9d42bf08b08ac18255db5170fe885cf3c37
```
=> feat(cli): vkey command to output program vkey hash

README.md, crates/prover/src/lib.rs
Minor changes:
Remove `unwrap` in the e2e test, and handle error as the e2e test returns `anyhow::Result`
=> chore(prover::tests): handle error instead of `unwrap` in e2e test

Cargo.lock, crates/core/machine/src/utils/mod.rs, crates/recursion/circuit-v2/src/build_wrap_v2.rs, crates/recursion/compiler/Cargo.toml, crates/recursion/compiler/src/circuit/compiler.rs, crates/recursion/core-v2/Cargo.toml, crates/recursion/core-v2/src/chips/alu_base.rs, crates/recursion/core-v2/src/chips/alu_ext.rs, crates/recursion/core-v2/src/chips/exp_reverse_bits.rs, crates/recursion/core-v2/src/chips/fri_fold.rs, crates/recursion/core-v2/src/chips/mem/constant.rs, crates/recursion/core-v2/src/chips/mem/variable.rs, crates/recursion/core-v2/src/chips/poseidon2_skinny/mod.rs, crates/recursion/core-v2/src/chips/poseidon2_wide/mod.rs, crates/recursion/core-v2/src/chips/public_values.rs, crates/recursion/core-v2/src/lib.rs, crates/recursion/core-v2/src/machine.rs, crates/recursion/core-v2/src/runtime/instruction.rs, crates/recursion/core-v2/src/runtime/memory.rs, crates/recursion/core-v2/src/runtime/mod.rs, crates/recursion/core-v2/src/runtime/program.rs
Additionally:
- Correct documentation for `sp1_debug_mode`.
- Calculate total memory used at compile time and reserve the memory in the runtime.
- Create a trait for Runtime's memory and two implementations, backed by `VecMap` and `Vec`. There is a `HashMap` implementation in the PR history, too. Currently, only the `VecMap` implementation is used.
Potential future improvements:
- Avoid converting between `Address<C::F>` and `usize` all the time in the compiler. This is probably really cheap, though.
- Avoid striping `Var`, `Felt`, and `Ext`. Currently they have different counters and are thus each assigned a residue class mod 3 to use for "virtual addresses."
=> perf: use crate `vec_map`, box large `Instruction` variants

crates/recursion/compiler/src/circuit/compiler.rs, crates/recursion/compiler/src/ir/builder.rs, crates/recursion/compiler/src/ir/types.rs
Enables a contiguous `VecMap` in the compiler.
Depends on #1371 and will need a rebase.
=> perf: unify variable counters

crates/helper/src/lib.rs
For backwards compatibility, add `BuildArgs` to the exported structs from `sp1-helper` (which is now deprecated).
=> chore: Add `BuildArgs` re-export to `sp1-helper`

.github/workflows/main.yml
fixes this:
```
Run cd cli
/home/runner/_work/_temp/0f6d5fad-2519-476c-a6c3-519453a159f8.sh: line 1: cd: cli: No such file or directory
```
=> fix: ci test examples

crates/recursion/core-v2/src/chips/poseidon2_wide/air.rs, crates/recursion/core-v2/src/chips/poseidon2_wide/columns/preprocessed.rs, crates/recursion/core-v2/src/chips/poseidon2_wide/trace.rs
I couldn't detect the performance change just by running the test, but reducing column count should be good.
=> perf: remove 15 cols from poseidon2 wide

crates/core/machine/src/cpu/air/memory.rs, crates/core/machine/src/cpu/columns/mod.rs, crates/core/machine/src/cpu/trace.rs
Handles the RISC-V spec rule of
`Loads with a destination of x0 must still raise any exceptions and cause any other side effects even though the load value is discarded.`
=> fix: handle load mem instructions that write to reg x0

crates/recursion/compiler/src/circuit/compiler.rs, crates/recursion/core-v2/src/chips/mem/constant.rs
`Imm` instructions now create aliases, i.e. multiple "virtual" addresses that point to a "physical" address.
=> perf: basic constant propagation for `Imm` instructions in v2 compiler

crates/recursion/compiler/src/circuit/compiler.rs
=> fix: avoid duplicate logic in `read_const`

crates/core/executor/src/executor.rs
We were running into a rare runtime issue where the runtime diverges from intended behavior when running from a checkpoint. Multiple checkpoints were halting, resulting in duplicate memory init/finalize records. Root cause is because mode is set to Simple in unconstrained mode, but checkpoint memory is only saved in Checkpoint mode.
Fix is to also save checkpoint memory if in unconstrained mode.
=> fix: memory not added to checkpoint in unconstrained mode

.github/workflows/pr.yml, crates/eval/src/lib.rs
Check `${{ github.ref == 'refs/heads/dev' }}` to determine if it's necessary to post to Slack. This reduces spam. 
Results are still updated every time on PRs.
=> ci: only post perfomance to slack on dev merge

crates/core/machine/src/syscall/precompiles/fptower/fp.rs
=> revert: "fix: add nonce constraint to fp"

.github/workflows/pr.yml, Cargo.lock, crates/eval/Cargo.toml, crates/eval/src/lib.rs, crates/eval/src/main.rs, crates/eval/src/program.rs
* include_bytes! so this crate can be imported in other and work
* setup_logger
* pass in prover opts
* arg PR name not needed
* use crates.io for slack-rust
=> chore: minor eval changes

crates/prover/src/lib.rs
this instrument line existed long ago, but got lost during some refactor.
Add it back here.
=> fix(log): add instrument for prover::compress

crates/build/src/build.rs
Closes: https://github.com/succinctlabs/sp1/issues/733
Commit msg fully describe that small change.
New error msg looks as follows:
```shell
Error: `cargo metadata` exited with an error: error: manifest path `/path/to/current/dir/Cargo.toml` does not exist
```
Unsure if test needed, tag me if so.
=> chore(build): friendly error msg when Cargo.toml is not found

book/writing-programs/precompiles.md
Documentation: Fixed broken link
=> docs: Fixed broken link

crates/sdk/src/network/client.rs, crates/sdk/src/network/prover.rs, crates/sdk/src/proto/network.rs
The prover network RPC will handle multiple versions.
=> feat: specify version in network client

Cargo.lock, crates/core/executor/Cargo.toml, crates/core/executor/src/executor.rs, crates/core/executor/src/opcode.rs, crates/core/executor/src/report.rs, crates/core/executor/src/syscalls/code.rs, crates/core/machine/src/riscv/cost.rs, crates/core/machine/src/utils/prove.rs, examples/patch-testing/script/src/main.rs
Uses the `enum-map` crate, which provides an associative array interface to an underlying array. It allocates memory proportional to the number of enum variants. In this case, those are the opcodes and syscalls, of which there are 47 and 35 of, respectively.
=> perf: optimize `ExecutionReport` and `create_alu_lookup_id` iff mode is trace

crates/sdk/src/network/auth.rs, crates/sdk/src/network/client.rs, crates/sdk/src/proto/network.rs
New network route `modify_cpu_cycles` for a prover to update the cycle count while proving
=> feat(sdk): send cpu cycles in network

crates/build/src/utils.rs
Fix the regression from https://github.com/succinctlabs/sp1/pull/1268 by correcting the file name.
=> fix: `copy_elf_from_output_dir` binary name

crates/cli/src/commands/build_toolchain.rs
The latest release of the Rust toolchain added a check for the target's existence in the bootstrap `rustc`, but allows a custom target to be specified via `RUST_TARGET_PATH`. This PR addresses this issue by providing a mock JSON target file.
=> fix: rust 1.81 toolchain build issue

.github/workflows/pr.yml, .github/workflows/toolchain-ec2.yml
Adds a CI job that checks installation toolchain with `cargo prove install-toolchain` and creating and compiling a new project.
Runs on all GitHub Actions runners that SP1 supports; also runs on Debian 12 using AWS EC2. More systems can be easily added by adding AMIs.
=> ci: test toolchain installation

examples/Cargo.lock, examples/fibonacci/script/Cargo.toml, examples/fibonacci/script/bin/groth16_bn254.rs
Using methods that return vectors or slices is more idiomatic.
=> chore: replace `raw()` with `bytes()` in fibonacci example

.github/actions/setup/action.yml, .github/workflows/docker-gnark.yml, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/release.yml, book/developers/usage-in-ci.md, crates/build/src/command/local.rs, crates/cli/src/commands/build_toolchain.rs, crates/core/executor/src/hook.rs, crates/recursion/core/src/range_check/mod.rs, crates/recursion/program/src/machine/deferred.rs, rust-toolchain
No good reason to stay on old Rust toolchain.
Also resolves new clippy lint warnings.
=> chore: upgrade Rust toolchain to 1.81.0

Dockerfile.gnark-ffi
The current cache mount in `Dockerfile.gnark-ffi` is broken:
1. It's mounting a cache dir at `/sp1/crates/recursion/gnark-cli/target` instead of `/sp1/target`, which is useless and as a result doesn't really cache anything. Any Docker build context changes would trigger a full rebuild.
2. It's not caching the Cargo registry. Even after fixing the issue above, any context change would still trigger a full dependency crate download. The correct solution is to also cache `/usr/local/cargo/registry`, which is the directory the build image uses for Cargo cache.
=> fix: gnark-ffi Dockerfile caching

crates/recursion/gnark-ffi/build.rs
The `sp1-recursion-gnark-ffi` crate's build script reruns when there are no changes. This is caused by the input header files from the Go compilation step above generating fresh header files each time. This PR solves the issue by turning the `rerun_on_header_files` option off.
=> fix: `sp1-recursion-gnark-ffi` rebuilds unnecessarily

crates/zkvm/entrypoint/src/lib.rs
The `interface` feature has been removed way back in https://github.com/succinctlabs/sp1/commit/e128143e9716d6457e67a06ba47646da439e1a10, but `sp1-zkvm` still uses it for a `cfg` section.
=> chore: remove non-existent feature

crates/build/src/build.rs, crates/build/src/utils.rs
The current ELF-copying behaviour assumes that the built artifact is named the same as the crate itself. This may not be true when using custom project structures.
Usually, when explicitly using a custom structure, devs know that they need to use the `--bin` option (or the `binary` field, programmatically). However, sometimes this can happen implicitly. For example, moving `src/main.rs` to `src/bin/hello.rs` implicitly creates a `bin` target named `hello`. Since this happens without explicitly configuring `Cargo.toml`, devs may not know they need to use `--bin`. Also, since it works with the normal `cargo build` users may expect it also works with `cargo prove build`.
This PR fixes it by utilizing the target collection logic added in #1620 to accurately identify the full path to the …
=> fix: build errors on custom bin target names

.github/workflows/docker-publish-gnark.yml, .github/workflows/docker-publish.yml, crates/build/src/lib.rs
The correct tag for pulling the Docker container that `sp1-build` should use is `latest`. `latest` should be created on every push to`main`.
While making this PR, I noticed that we don't trigger the `docker-publish.yml` and `docker-publish-gnark.yml` on pushes to main. This meant in the past that we manually set the `latest` tag. Now, we trigger the workflow on a push to `main`, which will auto-generate the `latest` tag.
=> fix(sp1-build, workflows): docker tag

crates/build/src/command/local.rs
Fixes #1629
I think only `CARGO_FEATURE_*` and `CARGO_CFG_*` need to be removed, but it's possible `DEP_*` should be removed as well. I don't have much experience with `cargo::metadata`, so not sure.
Regardless, those three are the only environment variables prefixes listed in [the docs](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts), and everything else should just get overridden by the inner `cargo` command.
=> fix: remove cargo environment vars from local build

crates/recursion/gnark-ffi/build.rs, crates/recursion/gnark-ffi/go/main.go, crates/recursion/gnark-ffi/src/ffi/native.rs
char pointers and struct pointers returned from go FFI to rust must be deallocated in go as well. Particularly, we were using `CString::from_raw` on char pointers allocated in go, [which is incorrect](https://doc.rust-lang.org/std/ffi/struct.CString.html#safety-1).
This PR exposes functions to free structs and strings allocated in go, and uses those instead.
=> fix: gnark-ffi memory handling

book/onchain-verification/contract-addresses.md, book/onchain-verification/getting-started.md, book/onchain-verification/solidity-sdk.md
Adds instructions for deploying to new chains, as well as finding your program vkey.
=> docs: update onchain usage

crates/sdk/src/proof.rs
Return empty bytes for both the `Groth16` and `Plonk` proofs if the `encoded_proof` is empty.
https://github.com/succinctlabs/sp1/pull/1297 did not handle the `Groth16` case.
=> fix: mock prover groth16 bytes

Cargo.lock, Cargo.toml, crates/zkvm/entrypoint/Cargo.toml, crates/zkvm/entrypoint/src/lib.rs
These additional checks ensure attempting to run an sp1 program on a non-zkvm host will silently noop instead of error.
=> fix: additional guards on entrypoint macro

sp1up/sp1up
sp1up now errors if you don't supply an argument after --version, --branch, etc.
sp1up now checks to make sure you download release tarball from the correct url
=> feat(sp1up): error messages for bad inputs.

.gitignore, crates/sdk/src/action.rs, crates/sdk/src/lib.rs, examples/Cargo.toml, examples/bls12381/program/Cargo.toml, examples/bls12381/script/src/main.rs, examples/bn254/program/Cargo.toml, examples/bn254/program/src/main.rs, examples/bn254/script/src/main.rs
Before, the sp1 program imported the bn and bls patches directly, like `bn = { git = "sp1-patches/bn" }`.
Now, they import the unpatched version, and the patch is applied from examples/cargo.toml
=> fix: patch bls and bn

book/getting-started/quickstart.md
Under executing the program, you have to switch directory from program to script. The example command does not work as a direct copy/paste because the user is in the /program dir and needs to go up one.  Just changing from "cd script"  to "cd ../script" would make life easier for newbies. 
And for the step of generating a proof, the "cd script" is repeated which fails when copy/pasted. Again "cd ../script" will work nicely here.
=> docs: Update example commands from cd script to cd ../script

Cargo.lock, Cargo.toml, crates/core/executor/src/executor.rs, crates/sdk/src/proof.rs, crates/sdk/src/provers/cpu.rs, crates/sdk/src/provers/cuda.rs, crates/sdk/src/provers/mock.rs
- Removes `stdin` field from `SP1ProofWithPublicValues`.
- Removes #[cfg(debug_assertions)] from self.log in the executor.
=> fix: remove stdin from SP1ProofWithPublicValues

crates/sdk/src/network-v2/client.rs, crates/sdk/src/network-v2/proto/network.rs, crates/sdk/src/network-v2/prover.rs
and set a different default cycle limit
=> chore: update network-v2 proto

book/generating-proofs/proof-types.md
Fix small typos in `generating-proofs.md`.
=> docs: `generating-proofs.md`

.github/ISSUE_TEMPLATE/BUG-FORM.yml, .github/ISSUE_TEMPLATE/FEATURE-FORM.yml, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
Add an issue template to the documentation.
Modeled off of https://github.com/foundry-rs/foundry/tree/master/.github/ISSUE_TEMPLATE
PR template from: https://github.com/alloy-rs/alloy/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1
=> feat: add issue template

Cargo.lock, crates/verifier/Cargo.toml
Uses the crates version of the bn patch instead of git.
=> chore: crates substrate_bn version

.github/workflows/pr.yml, Cargo.lock, crates/verifier/Cargo.toml, crates/verifier/src/error.rs, crates/verifier/src/groth16/ark_converter.rs, crates/verifier/src/groth16/error.rs, crates/verifier/src/groth16/mod.rs, crates/verifier/src/lib.rs, crates/verifier/src/plonk/error.rs, crates/verifier/src/tests.rs
Enable the `ark` feature to convert sp1 gnark proofs to arkworks structures.
=> feat: arkworks groth16 conversion

crates/core/executor/src/events/utils.rs, crates/core/executor/src/report.rs, crates/core/machine/src/utils/prove.rs, crates/core/machine/src/utils/span.rs
Printing unused syscalls just clutters the execution report
=> feat: stop printing unused syscalls in execution report

crates/core/executor/src/events/utils.rs, crates/core/executor/src/report.rs, crates/core/machine/src/utils/logger.rs, crates/core/machine/src/utils/prove.rs, crates/prover/src/lib.rs
1. Execute and prove_core end up printing out the same stuff twice, like cycle counts and syscall invocations. It's confusing for users to figure out if there should be a difference between these two outputs
2. A bunch of stuff about trace area for every table gets printed out, which users don't care about and is just confusing.
3. This refers more to the cuda prover I think: 
We could change the default to be RUST_LOG=sp1_cuda=off,info or something similarbi
=> feat: move a few logs to debug

crates/core/executor/src/context.rs, crates/core/executor/src/executor.rs, crates/core/executor/src/syscalls/verify.rs, crates/sdk/src/action.rs
Systems such as `op-succinct` require an additional flag to skip deferred proof verification when generating mock proofs, because their execution relies on the verification of compressed proofs (deferred proofs) which are invalid in mock mode.
=> feat: Add `skip_deferred_proof_verification`

book/SUMMARY.md, book/developers/rv32im-deviations.md, book/developers/rv32im-specification.md
Updates the RV32IM deviations section in the docs.
=> chore: rv32im deviations

crates/core/machine/src/memory/program.rs, crates/prover/src/lib.rs
ProgramMemory chip has a non-deterministic bug
Sort before generating preprocessed trace from HashMap
=> fix: preprocessed trace bug

.github/workflows/pr.yml, crates/prover/src/lib.rs
Workflows may cache some build artifacts, which may be cargo prove, which can cause this workflow to fail on toolchain install.
Force overwrite any binary, because caching appears to be non deterministic
=> fix: workflow should force install just in case

.github/workflows/book.yml
Right now, GH-pages only allows one site per repo, dev has been overriding main book deployments
closes #1820
=> chore: disable book for dev branch

crates/prover/src/types.rs
Adds docs for the HashableKey trait.
=> docs: hashablekey trait

crates/verifier/src/groth16/mod.rs, crates/verifier/src/plonk/mod.rs
=> fix: Remove unwraps inside `verify_gnark_proof` (issue 1830)

crates/sdk/src/cpu/builder.rs, crates/sdk/src/network/prove.rs, crates/sdk/src/network/prover.rs
For contexts where users are statefully tracking a set of proof requests and managing polling the proof requests manually, provide a `get_proof_status` method on the `NetworkProver`.
Users should be able to manually specify a `cycle_limit` if they're skipping simulation.
Add a `request` method to allows users to request a proof and get the proof ID back immediately.
Add `get_proof_status`, `request` and `cycle_limit` to the `NetworkProver`.
=> feat(sdk): `get_proof_status`, `request`, `cycle_limit`

CONTRIBUTING.md
Automated release tooling requires following the Conventional Commits format for commit messages and PR titles. Currently, the CONTRIBUTING.md file does not mention this requirement, causing confusion and failed checks for new contributors.
This PR adds a section in the "Commits" section of CONTRIBUTING.md to outline the Conventional Commits format. It includes examples and guidance so contributors know how to format their commits and PR titles correctly.
- [-] Added Tests (Not applicable for documentation changes)
- [-] Breaking changes (No breaking changes, just documentation)
=> docs: add conventional commit guidelines to CONTRIBUTING.md

book/versioned_docs/version-4.0.0/developers/common-issues.md
https://github.com/succinctlabs/rust/blob/db5963b699bf0b8d9bb826e700aa3cbd9593490b/.github/workflows/ci.yml#L17
Our rust toolchain is built on ubuntu 22.04 which links a newer version of `libc` than available on 20.04
=> chore: remove Ubuntu 20.04 workflow tests, docs 

book/versioned_docs/version-4.0.0/generating-proofs/prover-network/usage.md, book/versioned_docs/version-4.0.0/generating-proofs/prover-network/versions.md
- Add configuration for `SP1_PROVER` to `network`.
- Specify default RPC URL.
- Remove `3.X` as supported version.
=> fix(docs): network

crates/core/executor/src/syscalls/hint.rs, crates/zkvm/entrypoint/src/allocators/embedded.rs, crates/zkvm/entrypoint/src/lib.rs, crates/zkvm/lib/src/io.rs, crates/zkvm/lib/src/lib.rs
Previously, reading to much input would panic the executor and lead to ambiguous error messages, 
this change means that u32::MAX len vecs will fail. It displays the callsite of `read` or `read_vec`
=> feat: better failure messages when reading too much input

crates/build/src/command/local.rs
rustc includes a more helpful error on stderr:
> error: override toolchain 'succinct' is not installed: the RUSTUP_TOOLCHAIN environment variable specifies an uninstalled toolchain
also include stderr in panic
=> chore: include rustc --version stderr in panic

crates/core/machine/src/utils/mod.rs, crates/primitives/src/consts.rs
replace intermediary to_vec allocs with [`array::from_fn`](https://doc.rust-lang.org/stable/std/array/fn.from_fn.html) leveraging the available const generics
noticed these were duplicated, so I replaced the duplicated ones with re-exports
=> perf: rm vec allocs from words conversions

crates/sdk/src/network/prover.rs
Correctly validate the deadline against the current UNIX time.
=> feat(sdk): proof timeout fix

book/docs/getting-started/quickstart.md, crates/cli/src/commands/new.rs
Accelerate  `cargo prove new --evm`
Don't clone submodules, instruct the user to run `forge install` instead.
Also fixed the foundry detection.
=> feat: don't checkout submodules when doing `cargo prove new --evm`

Cargo.lock, crates/sdk/Cargo.toml
The issue arises because alloy-primitives features are being set to include all default features based on dependencies in OP Succinct. This causes a conflict with the kona dependency, which relies on the standard HashMap implementation.
Specifically:
1.	sp1-sdk enables all default features of alloy-primitives unnecessarily.
2.	This includes the map-foldhash feature, which uses foldhash::fast::RandomState.
3.	foldhash::fast::RandomState does not implement Send + Sync.
4.	However, spin::RwLock, which kona uses, requires its contents to be Send + Sync for thread safety.
This mismatch leads to thread-safety issues when foldhash::fast::RandomState is used in conjunction with spin::RwLock.
The solution is to disable default features for alloy crates in `sp1-sdk`, preventing it from enabling all …
=> feat(sdk): Turn off `alloy-*` crate features by default

book/docs/getting-started/install.md
Added an example command showing how to use GitHub token with sp1up command to resolve rate-limiting issues. This makes the installation documentation more complete and user-friendly by providing a concrete example of token usage.
Resolves TODO comment in installation guide.
=> docs: add GitHub token usage example in installation guide

crates/core/executor/src/dependencies.rs, crates/core/machine/src/air/mod.rs, crates/core/machine/src/memory/consistency/columns.rs, crates/recursion/core/src/air/memory.rs, crates/sdk/src/network/prove.rs, crates/zkvm/entrypoint/src/syscalls/mod.rs
applied some nightly clippy suggestions
=> chore(clippy): misc clippy fixes

crates/recursion/gnark-ffi/go/go.mod
>Caused by:
process didn't exit successfully: `/Users/Matthias/git/rust/sp1/target/debug/build/sp1-recursion-gnark-ffi-5c63451eec7e8a67/build-script-build` (exit status: 101)
--- stdout
cargo:rerun-if-changed=go
Building Go library at /Users/Matthias/git/rust/sp1/target/debug/build/sp1-recursion-gnark-ffi-d2e6560ead9a758e/out/libsp1gnark.a
>  --- stderr
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available
according to https://github.com/golang/go/issues/65568#issuecomment-1932597413
> go 1.22 without a more specific toolchain directive is not sufficient.
https://github.com/golang/go/issues/62278#issuecomment-1693538776
> this is as expected: go 1.21 was a development version of the language, for which there is no downloadable release (because …
=> fix: use downloadable go directive 1.22.0

.github/workflows/release.yml, .github/workflows/toolchain-ec2.yml, crates/core/executor/src/executor.rs, crates/core/executor/src/syscalls/verify.rs
* Currently, the entire ExecutionState.proof_stream is being cloned for every checkpoint, which is very wasteful for programs with many deferred proofs. Since it's only used as a runtime check, we can skip the clone and verification with checkpoints.
=> fix: deferred checkpoints optimization

patch-testing/Cargo.lock, patch-testing/Cargo.toml, patch-testing/RustCrypto-rsa/Cargo.toml, patch-testing/RustCrypto-rsa/program/Cargo.lock, patch-testing/RustCrypto-rsa/src/lib.rs, patch-testing/bls12-381/Cargo.toml, patch-testing/bls12-381/src/lib.rs, patch-testing/bn/Cargo.toml, patch-testing/bn/src/lib.rs, patch-testing/curve25519-dalek-ng/Cargo.toml, patch-testing/curve25519-dalek-ng/src/lib.rs, patch-testing/curve25519-dalek/Cargo.toml, patch-testing/curve25519-dalek/src/lib.rs, patch-testing/k256/Cargo.toml, patch-testing/k256/src/lib.rs, patch-testing/keccak/Cargo.toml, patch-testing/keccak/src/lib.rs, patch-testing/p256/Cargo.toml, patch-testing/p256/src/lib.rs, patch-testing/rustcrypto-bigint/Cargo.toml, patch-testing/rustcrypto-bigint/src/lib.rs, patch-testing/secp256k1/Cargo.toml, patch-testing/secp256k1/src/lib.rs, patch-testing/sha/Cargo.toml, patch-testing/sha/src/lib.rs, patch-testing/sp1-test-macro/src/attr.rs, patch-testing/sp1-test-macro/src/lib.rs
We need to ensure that the SP1 syscalls that we expect to be emitted with every patch are actually emitted.
Add a `syscalls` attribute to `sp1_test`, and ensure that the specified syscalls counts in the execution report are > 0.
=> test: check syscalls are actually emitted

crates/core/machine/src/riscv/mod.rs, crates/core/machine/src/utils/prove.rs
This PR consists of two fixes:
1. Fixes the event count for the Global chip in shape fixing logic.
2. When memory initialize and finalize records get pushed to the core shard, tries to fix the shape and if that fails resorts to the usual path (the current code just panics).
=> fix: counts and small shape fixing

Cargo.lock, crates/sdk/Cargo.toml
Bump `alloy-signer` dependencies to latest. Due to `alloy`'s `0.X` status, minor versions with different traits cause conflicts with one another.
https://github.com/op-rs/kona recently bumped to the latest `alloy` version, so in order to have `sp1-sdk` and `kona-host` in the same workspace, we need to bump `alloy-signer` and `alloy-signer-local` to `0.11`.
=> chore: bump alloy deps

crates/sdk/Cargo.toml
enable this feature for faster execution in curve-op heavy workloads.
=> chore: expose bigint rug feature in sdk

.github/workflows/pr.yml, crates/zkvm/entrypoint/src/allocators/embedded.rs, crates/zkvm/entrypoint/src/allocators/mod.rs
On OP Succinct workloads, `TLSFHeap` has been found to be empirically cheaper. This likely extends to most other workloads. In contrast to `LLSFHeap` (which could balloon to ~300-400% more cycles), `TLSFHeap` is generally capped at ~35% more cycles.
Switch to using `TLSFHeap` instead of `LLSFHeap`.
Source PR:  https://github.com/rust-embedded/embedded-alloc/pull/78
- `TLFSHeap` does not implement the `free` and `used` functions.
- Small CI fix for `Check Verifier no-std` job.
=> feat(sp1-zkvm): Switch `embedded-alloc` to use `TLSFHeap`

patch-testing/k256/program/bin/recover.rs, patch-testing/k256/src/lib.rs, patch-testing/p256/program/bin/recover.rs, patch-testing/p256/src/lib.rs, patch-testing/secp256k1/src/lib.rs
The test benchmarking requires a fixed number of iterations to be comparable. 
The benchmarker assumes old tests are equivalent, and uses old code to get the comparison cycle counts, therefore, either the old tests must be conducive to passing the number off to the benchmarker, or they can simply use a fixed number of iterations. 
For now, this PR does the latter.
=> fix: const test iterations

crates/build/src/build.rs, crates/build/src/lib.rs
closes #1979
The issue brings up a good point that error message currently provided when trying to use elf name without an output directory is not clear enough.
As we want to discourage copying of ELF files, and the use of `include_elf`/ build script flow, we require output directory is set if elf name is set.
We still do not allow elf name if multiple guest targets are found.
=> fix(cli): elf name requires output directory

.github/workflows/patch-testing-cycles.yml, patch-testing/sp1-test-macro/src/lib.rs, patch-testing/sp1-test/Cargo.toml, patch-testing/sp1-test/bin/post_to_github.rs, patch-testing/sp1-test/src/lib.rs, patch-testing/sp1-test/src/utils.rs
This PR adds a CI workflow to compare cycle counts if there are changes to `patch-testing/*`. 
Note: Some tests are non deterministic in their cycle count.
=> feat(ci): patch ci cycle check

crates/core/machine/build.rs
Gets rid of some old debugging code. The similar build script in recursion is already set up like this.
=> chore(core): re-ignore syntax errors to allow diagnostics to run

crates/core/machine/src/syscall/precompiles/README.md
The documentation for precompiles is missing some critical content, particularly regarding how to update costs and expose syscalls. For developers and contributors who wish to add custom precompiles, these missing parts can lead to a frustrating experience.
Add the missing content, including updates on costs and exposing syscalls.
=> docs: improve precompiles doc

crates/sdk/src/network/prove.rs
Changes
```rust
self.prover
.prove(&self.pk, &stdin)
.strategy(FulfillmentStrategy::Reserved)
.skip_simulation(true)
.plonk()
.timeout(Duration::from_secs(PROOF_TIMEOUT_SECS))
.run_async()
.await
```
to 
```rust
self.prover
.prove(&self.pk, &stdin)
.strategy(FulfillmentStrategy::Reserved)
.skip_simulation(true)
.plonk()
.timeout(Duration::from_secs(PROOF_TIMEOUT_SECS))
.await
```
=> feat(sdk): Implement `IntoFuture` for `NetworkProveBuilder`

crates/recursion/gnark-ffi/src/ffi/docker.rs
Improve observability if Docker call fails.
Helps with #2059
=> fix(recursion): include stderr from Docker in errors

crates/verifier/src/constants.rs, crates/verifier/src/groth16/converter.rs, crates/verifier/src/groth16/mod.rs, crates/verifier/src/plonk/converter.rs, crates/verifier/src/plonk/mod.rs, crates/verifier/src/tests.rs
On sp1-verifier, Groth16Verifier and PlonkVerifier, the verify function directly slices arrays that can cause panic. 
Check the slices length and return an `InvalidData` error.
Closes #1920
=> feat: avoid panic when verify Groth16 and Plonk proofs

crates/cuda/src/lib.rs
`Stdio::inherit` pipes the selected `io` to the parent process, this PR takes advantage of this, rather than manually spawning new threads to do the piping.
=> chore(cuda): cleanup stdio piping

crates/zkvm/entrypoint/src/syscalls/memory.rs
For benchmarks it would be useful to have a way to access the memory usage in the zkvm, when using the bump global allocator
Adding a `used_memory()` function that returns the used memory.
=> feat: give access to used memory in the zkvm

.github/actions/setup/action.yml, .github/workflows/docker-gnark.yml, .github/workflows/executor-suite.yml, .github/workflows/main.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/suite.yml, Dockerfile.gnark-ffi, crates/core/executor/src/executor.rs, crates/core/executor/src/lib.rs, rust-toolchain.toml
I believe that `rustup` used to install the override by default via any `rustup` command, however it is now throwing errors that the override toolchain is not installed!
=> fix(ci): rust toolchain override to `stable`

crates/core/executor/src/report.rs, crates/core/executor/src/syscalls/write.rs
Sometimes, when using report annotations, we need to know the invocation count. My use case was to be able to track the average precompiles and opcodes cycles count.
Adding a `invocation_tracker` map that increment by 1 for the given label each times the `ReportEnd` command is called.
=> feat: track invocation count

crates/sdk/src/network/client.rs, crates/sdk/src/network/mod.rs, crates/sdk/src/network/proto/network.rs, crates/sdk/src/network/prove.rs, crates/sdk/src/network/prover.rs, crates/sdk/src/prover.rs
It's preferable to use `gas_limit` in the network instead of `cycle_limit`.
Add `gas_limit(...)` to prover builder, and make it similar to `cycle_limit` in terms of simulation.
=> feat(sdk): set gas limit for network

crates/core/executor/src/context.rs, crates/core/executor/src/executor.rs
Fix `max_cycles` limit check when running and proving programs with a context.
When a user runs a program, gets the report, takes `report.total_instruction_count()`, uses it as `max_cycles` and tries to run the same program with it, it does not work. 
The check if `max_cycles` was exceeded, is currently off by 1:
```rust
if self.state.global_clk >= max_cycles {
return Err(ExecutionError::ExceededCycleLimit(max_cycles));
}
```
This breaks at the very last legitimate cycle if `max_cycles` is set to the exact number of the program cycles.
This PR fixes the check to be `if self.state.global_clk > max_cycles {`, because 
`self.state.global_clk == max_cycles` is still ok.
=> fix: correct max_cycles limit check

crates/cli/src/commands/new.rs
If the directory already exists, the error for `cargo prove new` isn't informative.
```
cargo prove new fibonacci --bare
Cloning https://github.com/succinctlabs/sp1-project-template
Error: failed to clone repository:
```
This change allows properly catching the `stderr` and piping it in the error message.
=> chore: cargo prove new

crates/core/executor/src/context.rs, crates/core/executor/src/executor.rs, crates/core/executor/src/syscalls/write.rs, crates/sdk/src/cpu/execute.rs, crates/sdk/src/cpu/prove.rs, crates/sdk/src/lib.rs, crates/test-artifacts/programs/Cargo.lock, crates/test-artifacts/programs/Cargo.toml, crates/test-artifacts/programs/hello-world/Cargo.toml, crates/test-artifacts/programs/hello-world/src/main.rs, crates/test-artifacts/src/lib.rs
Closes #2121
While IO options implements `Clone` for backwards compatibility, we should decide if this really is needed, if it is, we should document that `IOOptions` clone impl resets to `None`, as writers require exclusive access. 
The other option would be to wrap it in a mutex, which is not ideal.
=> feat(executor): Add overrides to std{io, err} for guest programs

crates/cuda/src/lib.rs, crates/perf/src/main.rs, crates/sdk/src/client.rs, crates/sdk/src/cuda/builder.rs, crates/sdk/src/cuda/mod.rs, crates/sdk/src/env/mod.rs
In order to be able to prove with Cuda from inside a container, we need to be able to specify a Moongate server endpoint instead of starting a container it when creating a Cuda prover.
A possible use case would be with Docker compose that includes the Moongate container.
When the `SP1_MOONGATE_ENDPOINT` env variable is provided, use it to connect to the Moongate server instead of creating a container.
=> feat: allow to use an existing Moongate server

crates/sdk/src/network/client.rs
Fixes this error that can occur during client creation:
> thread 'tokio-runtime-worker' panicked at script/src/main.rs:309:77:
failed to generate compressed proof: transport error
Caused by:
0: dns error: failed to lookup address information: nodename nor servname provided, or not known
1: dns error: failed to lookup address information: nodename nor servname provided, or not known
2: failed to lookup address information: nodename nor servname provided, or not known
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Error: JoinError::Panic(Id(52), "failed to generate compressed proof: transport error\n\nCaused by:\n   0: dns error: failed to lookup address information: nodename nor servname provided, or not known\n   1: dns error: failed to lookup address …
=> fix(sdk): retry network client creation failures

sp1up/install
While trying to run my sp1up install script on my Mac, I was sort of losing it because I didn't have OpenSSL. The script performs two separate checks for required libraries under macOS: the first one is right to give a warning about missing libusb, but the second one (for OpenSSL) is wrong in copying the libusb warning. 
This pull request corrects the sp1up install script so the OpenSSL check will print the correct warning message. The message has been revised to:
> "warning: openssl not found. You may need to install it manually on MacOS via Homebrew (brew install openssl)."
This fix should prevent mac users from being confused and spare others the frustration I had to endure.
=> fix(sp1up): correct openssl warning message in install script

Dockerfile.build
To support reproducible ELFs for celestia DA in op-succinct, protobuf-compiler is needed.
Add protobuf-compiler to Dockerfile.build dependency.
-  ~Added Tests~
- ~Added Documentation~
=> chore: add protobuf-compiler to Dockerfile.build dep

Dockerfile.build
Reverting changes from #2193, since it was too ad hoc to celestia support in op-succinct.
Chose to remove protobuf dep from celestia program.
=> chore: remove protobuf-comiler to Dockerfile.build dep

crates/build/src/build.rs, crates/build/src/command/docker.rs, crates/build/src/command/local.rs, crates/build/src/lib.rs
This commit introduces `WarningLevel` in `BuildArgs` to allow suppressing the non-essential warning messages in the build process. The default value of `WarningLevel` is `All`, i.e., all warning messages are displayed, making the existing behavior unchanged. Users can specify `WarningLevel::Minimal` in `BuildArgs` to skip the non-critical messages mentioned in #2186.
Close https://github.com/succinctlabs/sp1/issues/2186
=> feat: introduce `WarningLevel`

crates/core/machine/src/shape/mod.rs
When building SP1 from a repo cloned when the git config setting `core.symlinks` is set to false, the `rv32im_costs.json` file (that is a symlink) can't be loaded.
Adding an hint of the root cause in the error message.
Closes #2170
=> chore: improve error message for rv32im_costs.json loading failure

Cargo.lock, crates/verifier/Cargo.toml
closes #2225
Cargo sees `0.6.0-v4.1.4` as a pre-release of version `0.6.0`. This means a fresh Cargo.lock will select `0.6.0` which imports an old version of `sp1-lib`
The problem were seeing is people who are trying to use `sp1-verifier` crate are hitting old file descriptors.
=> fix(sp1-verifier): strict BN version

.github/workflows/pr.yml, crates/sdk/src/env/mod.rs, crates/sdk/src/utils.rs
Teams that run benchmarks might forget the release flag and see degraded performance. To avoid that, we want to disallow provers to be ran in debug in CPU and Cuda mode.
Panics when the CPU and Cuda provers are instantiated if `sp1-sdk` is build in debug. It's not an issue with the network prover as progams are executed on a remote cluster.
=> feat: disallow SP1 to be ran in debug

.github/workflows/pr.yml, Cargo.lock, Cargo.toml, crates/primitives/Cargo.toml, crates/primitives/src/io.rs, crates/prover/src/verify.rs, crates/sdk/Cargo.toml, crates/sdk/src/prover.rs, crates/test-artifacts/programs/Cargo.lock, crates/test-artifacts/programs/fibonacci-blake3/Cargo.lock, crates/verifier/Cargo.toml, crates/verifier/src/groth16/mod.rs, crates/verifier/src/plonk/mod.rs, crates/verifier/src/tests.rs, crates/verifier/src/utils.rs, patch-testing/Cargo.lock
`verify()` fails on proofs when `sp1-zkvm` `blake3` feature is enabled.
Remove the `blake3` feature everywhere except in `sp1-zkvm`, and when we want to verify PV, check with both Sha256 and Blake3 hashing.
=> fix: allow to use blake3 to hash PV

crates/core/executor/src/syscalls/write.rs
Update the link for the patched crates, which changed with the recent docs re-organization.
=> docs(executor): patched crates link

crates/sdk/src/cuda/mod.rs
For applications like ETHProofs, we don't want to execute twice to get the cycle count and it'd be nice to return it to reduce our latency.
Add a `prove_with_cycles()` fn on `CudaProver` that returns a tuple with the proof and the cycle count.
=> feat: give access to cycle count when using CudaProver

crates/sdk/src/network/prover.rs
Users who use `get_proof_status` on SP1 SDK `4.2.0` encounter a `failed to deserialize proof` issue when calling `get_proof_status`.
This method is uncommonly used (as the default `prove` path calls `process_proof_status`), and the changes in https://github.com/succinctlabs/sp1/pull/2204 forgot to update `get_proof_status` when updating `process_proof_status`.
Deserialize into `ProofFromNetwork` in `get_proof_status`, then map into `SP1ProofWithPublicValues`.
=> fix(`get_proof_status`): Deserialize into `ProofFromNetwork`

crates/cuda/proto/api.proto, crates/cuda/src/lib.rs, crates/cuda/src/proto/api.rs, crates/sdk/src/cuda/mod.rs
When proving with Cuda, calling `prove()` only work with the last program that was registered with `setup()`.
Sends the ELF with each `prove()` request, and lazily call `setup()`on the Moongate server if the program is not already registered. 
Closes #2247, #2180
=> feat: stateless proving with Moongate

.github/workflows/pr.yml, Cargo.lock, crates/verifier/Cargo.toml
The latest version of BitVM uses arkworks v0.5.0, while SP1 rely on v0.4.x, which prevents us from using the latest BitVM with sp1 altogether.
Update arkworks dependencies to `v0.5.0`.
Closes #2275
=> chore: update arkworks dependencies

crates/build/src/command/docker.rs, crates/build/src/command/local.rs
The `CFLAG` `-D__ILP32__` has been added in #2185 to allow zkVM programs that depends on `ring` to build, but the flag is also active during the build script compilation (that not occurs inside the zkVM), leading to build errors.
Use the `CFLAGS` variant that include the `riscv32im_succinct_zkvm_elf` target in order to add `-D__ILP32__` only when needed.
Closes #2274
=> fix: add `-D__ILP32__` in zkvm only

crates/sdk/src/install.rs
PLONK / Groth16 circuits artifact location can't be customized.
This could be beneficial in settings where we deploy the prover as binary artifacts, say when packaging up inside a jar or potentially even in mobile apps.
Closes #2280
Adding `SP1_GROTH16_CIRCUIT_PATH` and `SP1_PLONK_CIRCUIT_PATH` env variables that overrides default path if specified.
=> feat: allow to customize circuits paths

.github/workflows/release.yml
Ubuntu 20.04 LTS runner will be removed on 2025-04-15.
=> chore: Ubuntu 20.04 retirement

crates/sdk/src/network/mod.rs, crates/sdk/src/network/prover.rs, patch-testing/Cargo.lock
[network.succinct.xyz](https://network.succinct.xyz/) has been deprecated and replaced with [explorer.succinct.xyz](https://explorer.succinct.xyz/) and [explorer-private.succinct.xyz](https://explorer-private.succinct.xyz/) (used by Succinct customers who need private inputs).
Display the correct explorer both when the default network RPC is used, and when one is passed by the user.
The log will show this:
```
2025-06-13T22:28:17.263550Z  INFO Requesting proof:
2025-06-13T22:28:17.263580Z  INFO ├─ Cycle limit: 20000000000
2025-06-13T22:28:17.263582Z  INFO ├─ Gas limit: 1000000000
2025-06-13T22:28:17.263583Z  INFO ├─ Proof mode: Compressed
2025-06-13T22:28:17.263584Z  INFO ├─ Strategy: Hosted
2025-06-13T22:28:17.263585Z  INFO ├─ Timeout: 14400 seconds
2025-06-13T22:28:17.263585Z  INFO └─ …
```
=> fix: log correct network explorer links

crates/sdk/Cargo.toml, crates/sdk/src/network/prover.rs, examples/Cargo.lock
avoids
```
thread 'main' panicked at /Users/ctian/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.27/src/crypto/mod.rs:249:14:
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
```
error (which happens when rustls has `aws-lc-rs` and `ring` features enabled) by trying to install ring provider in `NetworkProver::new()`
=> fix(sdk): try to install rustls CryptoProvider

crates/sdk/src/network/prover.rs
Remove semicolon to fix `expected Result<(), Error>, found ()`
=> fix(sdk): cancel_request result

crates/verifier/src/groth16/converter.rs, crates/verifier/src/groth16/mod.rs
Hey, SP1 team. For the purpose of reducing on-chain cost, we had to use compressed gnark groth16 proof, and verify it within SP1 VM. In this case, we have to enable loading compressed gnark groth16 proof. Thank you
=> feat: support compressed gnark groth16 proof

Cargo.lock, Cargo.toml, crates/core/executor/src/lib.rs, crates/sdk/Cargo.toml, crates/test-artifacts/programs/Cargo.lock, crates/test-artifacts/programs/fibonacci-blake3/Cargo.lock, crates/verifier/guest-verify-programs/Cargo.lock, examples/Cargo.lock, patch-testing/Cargo.lock, patch-testing/secp256k1/program-v0.29.1/Cargo.lock, patch-testing/secp256k1/program-v0.30.0/Cargo.lock
We need a `sp1-sdk` release to make private proving available.
I also added back SP1ReduceProof in sp1-core-executor as it was removed in #2450, but needed [in hokulea](https://github.com/Layr-Labs/hokulea/blob/2dae748c69d7ace01ab1c1ff471e87449371893d/canoe/sp1-cc/host/src/lib.rs#L99)
=> chore: bump sdk to v5.2.2
