book/theme/head.hbs

fix: #243
Updated the image link, but not sure how to test this...

fix: hbs image

---

.github/workflows/tests.yml
core/src/stark/machine.rs
core/src/stark/prover.rs
core/src/utils/prove.rs

Fixes previous issues and runs a single test to ensure we can still compile for non-default features.

fix: non-default feature errors and check during ci

---

book/generating-proofs/advanced.md
book/getting-started/quickstart.md
cli/src/assets/script/main.rs
cli/src/commands/build_toolchain.rs
cli/src/commands/install_toolchain.rs
examples/chess/script/src/main.rs
examples/cycle-tracking/script/src/main.rs
examples/ed25519/script/src/main.rs
examples/fibonacci-io/script/src/main.rs
examples/fibonacci/script/src/main.rs
examples/io/script/src/main.rs
examples/is-prime/script/src/main.rs
examples/json/script/src/main.rs
examples/regex/script/src/main.rs
examples/rsa/script/src/main.rs
examples/ssz-withdrawals/script/src/main.rs
examples/tendermint-benchmark/script/src/main.rs
examples/tendermint/script/src/main.rs

Not a priority, it just bothered me :)

chore: Typo in 'successfully' corrected across all instances

---

Cargo.lock
Cargo.toml
core/src/utils/prove.rs
recursion/compiler/src/gnark/lib/main.go

Adapt to the latest uni-stark changes.

feat: plonky3 update 

---

cli/src/assets/program/main.rs
cli/src/assets/script/main.rs

fix: outdated templates

---

Cargo.lock
core/Cargo.toml
core/src/stark/permutation.rs
examples/fibonacci/script/Cargo.lock

feat: small permutation trace gen perf opt

---

.github/workflows/tests.yml

Add `cargo prove new` to CI, as several users have had this break due to API changes in `sdk`.
https://github.com/succinctlabs/sp1/pull/542

feat(ci): add `cargo prove new` to ci

---

core/src/air/sub_builder.rs

Technically `row` seemed wrong before (just passed along the whole row). Also `row_slice` can be simplified.

fix: some SubBuilder tweaks

---

.github/dependabot.yml

This useful to get automatic dependency updates.

ci: set up dependabot

---

.github/workflows/pr.yml
cli/src/assets/program/Cargo.toml
cli/src/assets/script/Cargo.toml

Reset the branch of `sp1` used in `cargo prove new` to `main`. Additionally, modify the `pr` workflow to add the local `sp1-zkvm` branch.

fix: assets branch

---

sdk/src/provers/local.rs

Update `plonk` feature disabled message.

chore: plonk feature disabled

---

.github/workflows/release.yml

- Update name on latest release to `Latest`
- Set `latest` tag to pre-release

chore: release workflow changes

---

.github/workflows/pr.yml

Don't active `pr` workflow on push to `dev`.

chore: pr workflow

---

book/verifying-proofs/solidity-and-evm.md

Link to documentation for installing SP1 contracts in the SP1 docs.

docs: Instructions for installing SP1 contracts

---

sdk/src/network/auth.rs
sdk/src/network/client.rs
sdk/src/network/prover.rs
sdk/src/proto/network.rs

Client version must match with the supported version on the network

feat: check version for proof requests

---

book/SUMMARY.md
book/generating-proofs/network.md

updated guide to using the prover network, including whitelisted form

docs: updated prover network guide

---

recursion/gnark-ffi/go/sp1/babybear/babybear.go
recursion/gnark-ffi/go/sp1/build.go
recursion/gnark-ffi/go/sp1/poseidon2/constants.go
recursion/gnark-ffi/go/sp1/poseidon2/poseidon2.go
recursion/gnark-ffi/go/sp1/poseidon2/poseidon2_babybear.go
recursion/gnark-ffi/go/sp1/poseidon2/poseidon2_test.go
recursion/gnark-ffi/go/sp1/poseidon2/utils.go
recursion/gnark-ffi/go/sp1/prove.go
recursion/gnark-ffi/go/sp1/sp1.go
recursion/gnark-ffi/go/sp1/verify.go
recursion/program/src/machine/utils.rs

Fixed "comments with typos and outdated information", "excess visibility", "dead code".

fix: some informational fixes from veridise audit

---

recursion/gnark-ffi/assets/SP1Verifier.txt

Plonk verifier also throws a bool that should be checked

fix(contracts): check verifier success

---

cli/src/lib.rs

Present more informative logging message when installing the SP1 toolchain.

docs(cli): informative logging

---

sdk/Cargo.toml
sdk/src/provers/mock.rs

mock compressed that was missing

feat(sdk): finish mock prover implementation

---

core/src/air/extension.rs

Forgot to remove this extra code.

fix: remove extra `try_inverse` in #1014

---

book/SUMMARY.md
book/prover-network/versions.md

Redirecting prover network version mismatch errors to this page

docs: supported prover network versions

---

book/writing-programs/setup.md

Instructions on building with `--tag`

docs: using --tag to specify a release

---

sdk/src/action.rs

fix warning message showing up because default options mismatch

fix(sdk): options warning when using network prover

---

book/writing-programs/patched-crates.md

Docs for https://github.com/sp1-patches/RustCrypto-bigint patched crate

docs: add bigint patched crate

---

book/writing-programs/patched-crates.md

Adds sha3 patches from https://github.com/sp1-patches/RustCrypto-hashes

docs: add sha3 patched crate

---

sp1up/install
sp1up/sp1up

need consistent, predictable location for sp1 dir

chore: remove XDG_CONFIG_HOME from sp1up

---

.github/workflows/docker-gnark.yml
.github/workflows/main.yml
.github/workflows/pr.yml
.github/workflows/release.yml

Fix indefinite queueing and slow startup time: https://runs-on.com/guides/troubleshoot/

fix(ci): `runs-on` configuration 🚀

---

book/developers/rv32im-specification.md
book/writing-programs/patched-crates.md

fixes https://github.com/succinctlabs/sp1/actions/runs/10222961071/job/28288491356
```
Run mdbook-linkcheck --standalone
error: Linking outside of the "root" directory is forbidden
┌─ writing-programs/patched-crates.md:129:40
│
129 │ An example of this is available in our [Patch Testing Example](../../examples/patch-testing/script/src/main.rs).
│                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Linking outside of the "root" directory is forbidden
warning: Potential incomplete link
┌─ developers/rv32im-specification.md:7:45
│
7 │ - Memory access is only valid for addresses [0x20, 0x78000000]. Accessing addresses outside of this range will result in undefined behavior. The global heap allocator in `sp1_zkvm` will panic if memory …
```

docs: fix lint issues

---

sp1up/install

```
🚀 Installing sp1up...
################################################################################################################################################################ 100.0%
✅ Installation complete!
🔍 Detected shell: zsh
🔗 Added sp1up to PATH
To start using sp1up, please run:
▶ source /Users/jtguibas/.zshenv
▶ sp1up
🎉 Enjoy using sp1up! For help, type 'sp1up --help'
```

chore: improve sp1up output

---

README.md

Addresses #1282. 
SP1 is built on the shoulder of an enormous amount of open-source work. We're happy to give credit to prior work. We have done so in our announcements both on our [blog](https://blog.succinct.xyz/introducing-sp1/#:~:text=Acknowledgements,inspired%20our%20work) and [twitter](https://x.com/SuccinctLabs/status/1757832264325738909). 
We recently removed this section from the README (didn't really think much of it at the time), but after community feedback we're adding it back.

feat: acknowledgments in README

---

crates/build/src/lib.rs
crates/cli/docker/Dockerfile

This helpers users not have to manually set these everytime, such as https://github.com/taikoxyz/raiko/blob/959bdeadfc216e76ee512cab38f9ab560dea237c/provers/sp1/builder/src/main.rs#L42-L44

feat: default strict align CFLAGS

---

book/getting-started/install.md

make the build from source part reflect the folder structure.

chore: fixing install guide

---

crates/sdk/src/action.rs

I wanted to try groth16 in `upa-sp1-project-template`

feat: add groth16 to Prove

---

sp1up/sp1up

so that `sp1up --token ...` works

fix: pass github token into install-toolchain

---

crates/recursion/compiler/src/circuit/compiler.rs

Use a `BTreeMap` instead of a `HashMap` for constants in the compiler. This ensures that it is deterministic.

fix: make v2 compiler deterministic

---

crates/zkvm/entrypoint/Cargo.toml
crates/zkvm/lib/Cargo.toml

bad README paths prevent crate publishing, this fixes

fix: zkvm readme paths

---

crates/core/machine/src/syscall/precompiles/fptower/fp.rs

revert: "revert: fix: add nonce constraint to fp"

---

crates/recursion/gnark-ffi/assets/SP1VerifierGroth16.txt
crates/recursion/gnark-ffi/assets/SP1VerifierPlonk.txt
crates/recursion/gnark-ffi/src/groth16_bn254.rs
crates/recursion/gnark-ffi/src/plonk_bn254.rs

no adjustments needed to deploy the verifiers anymore

feat: automatic solidity verifier adjustments

---

crates/cuda/src/lib.rs
crates/sdk/src/lib.rs
crates/sdk/src/provers/cuda.rs

- feat: timeout waiting for the server to start and panic
- refactor: don't use sudo when starting Docker container

refactor: removed use of sudo + docker from cuda crate

---

book/why-use-sp1.md

Linked more example repos of SP1 usage

docs: why-use-sp1.md

---

crates/recursion/gnark-ffi/build.rs

Revert "chore: merge dev"

---

.github/workflows/pr.yml
book/generating-proofs/proof-types.md
crates/cli/src/commands/new.rs

feat(cli): improve `cargo prove new`

---

crates/cuda/src/lib.rs

current code will just ignore any stderr msgs from docker

fix(cuda-prover): dont discard stderr

---

Cargo.lock
crates/sdk/src/lib.rs

feat: allow run in dev mode

---

book/developers/common-issues.md

- Consolidate the bugs related to compiling in `release` mode.
- Add the `rc` tag issue.
- Make it clear that the most recent release of the Succinct Rust toolchain is `1.81`.

docs: common issues

---

Cargo.lock
crates/sdk/Cargo.toml
crates/sdk/src/network-v2/client.rs
crates/sdk/src/network/client.rs

feat(sdk): download proof from public URI

---

book/onchain-verification/contract-addresses.md

https://github.com/succinctlabs/sp1-contracts/pull/34

docs: separate SP1VerifierGateway for PLONK and Groth16

---

Cargo.lock
Cargo.toml
crates/verifier/Cargo.toml

Fixes verifier crate to use crates.io version of bn patch.

feat: fix for verifier crate

---

README.md

Fixes README.md broken link
Install now points to https://docs.succinct.xyz/docs/getting-started/install

Fix README.md install link

---

.github/actions/setup/action.yml
Cargo.lock
crates/sdk/Cargo.toml
crates/sdk/src/network/prover.rs

Remove Docker setup, as it's not necessary in setup CI.

fix(ci): remove docker login

---

book/docs/writing-programs/patched-crates.md

Fix the `ecdsa-core`, `bls12-381` and `substrate-bn` patches.

fix: v2 signatures patch

---

book/docs/writing-programs/patched-crates.md

chore(book): Add patch for sha2 `0.9.9`

---

.github/workflows/release.yml

- we build c/cpp in the core machine build script
- cc for whatever reason cannot detect defaults for this target correctly
-

fix: musl builds 

---

book/docs/developers/common-issues.md
book/docs/writing-programs/patched-crates.md
book/versioned_docs/version-4.0.0/developers/common-issues.md
book/versioned_docs/version-4.0.0/writing-programs/patched-crates.md

- Add `secp256r1` acceleration docs.

docs(patches): add secp256r1 section

---

crates/core/machine/build.rs

fix(core/machine): dont panic if target dir detection fails

---

crates/sdk/src/env/mod.rs

fix(sdk): implemented verify for EnvProver

---

crates/sdk/src/network/client.rs

WARN Network temporarily unavailable when requesting proof due to failed nonce verification: invalid nonce for sender 0x0e4dbeb1c43bccf169d0d22ff074b943fab2e07c expected 138, got 137, retrying...

fix(sdk): retry network request proof

---

book/docs/generating-proofs/prover-network/usage.md

fix: typo in prover network docs

---

book/docs/writing-programs/inputs-and-outputs.mdx

Replaces https://github.com/succinctlabs/sp1/pull/1840, as it's gone stale.

docs: `read_vec`

---

.github/workflows/release.yml
.github/workflows/toolchain-ec2.yml

Add description for workflow patch https://github.com/succinctlabs/sp1/pull/1973

docs(ci): Workflow patch documentation

---

Cargo.lock
crates/sdk/Cargo.toml
crates/sdk/build.rs
patch-testing/Cargo.lock

Closes https://github.com/succinctlabs/sp1/issues/2032.

chore(sdk): remove vergen dep

---

Cargo.toml
crates/cuda/src/lib.rs
crates/perf/workflow_prove.sh
crates/sdk/src/network/builder.rs
patch-testing/sp1-test/src/utils.rs

This PR bumps the CUDA prover docker image to the newest verison, it also includes a QOL improvement in the SDK if an empty private key is submitted.
The patch-testing cycle tracking workflow is updated to display reductions in cycles with a negative value.

feat: v4.1.0-dev

---

book/docusaurus.config.ts

chore: disable algolia temporarily

---

crates/core/executor/src/executor.rs

Fixes a bug where the max_cycles check includes unconstrained cycles.

fix: executor global_clk cycle count tracking

---

crates/build/src/command/docker.rs
crates/build/src/command/local.rs

Currently, our build commands overrides the entire toolchain, this is an issue since our latest release didnt include `host-tools`.
This PR changes the build command to search for the sysroot and override the rustc bin.

fix(build): override rustc only, not the entire toolchain

---

examples/Cargo.lock
examples/aggregation/script/src/main.rs

Fixes the aggregation example on GPU which runs into a buggy edgecase inside the GPU prover image. This is a short-term fix, we should instead fix it inside the GPU prover image.

fix: aggregation example on gpu

---

crates/core/machine/src/shape/mod.rs
crates/core/machine/src/utils/prove.rs
crates/prover/src/lib.rs
crates/prover/src/shapes.rs

In several places, we emit `info` logs that should instead be `debug`. Users do not need these logs.

chore: fix logging

---

crates/build/src/lib.rs
crates/prover/scripts/find_maximal_shapes.rs
crates/prover/scripts/find_oom_shapes.rs
crates/prover/scripts/find_recursion_shapes.rs
crates/prover/scripts/find_small_shapes.rs
crates/prover/scripts/test_shape_fixing.rs

The motivation for this PR is mainly to avoid bots and farmers submit this update over and over again.
Closes #2164

chore: don't use deprecated clap attributes

---

Cargo.lock
Cargo.toml
crates/test-artifacts/programs/Cargo.lock
crates/test-artifacts/programs/fibonacci-blake3/Cargo.lock
patch-testing/Cargo.lock

chore: bump to version 4.1.7

---

patch-testing/Cargo.lock
patch-testing/Cargo.toml
patch-testing/secp256k1/program/Cargo.toml
patch-testing/sp1-test-macro/src/lib.rs

The patch was never updated to use the new 4.1.0 k256 patch

fix(patches): 4.1.0 secp256k1 patch

---

Cargo.lock
Cargo.toml
Dockerfile.build
crates/test-artifacts/programs/Cargo.lock
crates/test-artifacts/programs/fibonacci-blake3/Cargo.lock
patch-testing/Cargo.lock

Releases v4.2.0, which includes support for SP1 TEE.

feat: release v4.2.0

---

crates/build/src/command/docker.rs
crates/build/src/command/local.rs
sp1up/sp1up

Until now it wasn't possible to build programs that depends on `ring`. Linking is failing with:
```
[sp1]    cargo:warning=In file included from /home/aurel/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ring-0.17.14/include/ring-core/base.h:26,
[sp1]    cargo:warning=                 from /home/aurel/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ring-0.17.14/include/ring-core/mem.h:18,
[sp1]    cargo:warning=                 from /home/aurel/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ring-0.17.14/crypto/curve25519/curve25519.c:22:
[sp1]    cargo:warning=/home/aurel/.sp1/riscv/riscv32im-linux-x86_64/lib/gcc/riscv32-unknown-elf/11.2.0/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
[sp1]    cargo:warning=    9 | # include_next <stdint.h>
[sp1] …
```

fix: handle guest programs that depends on ring

---

patch-testing/Cargo.lock
patch-testing/RustCrypto-rsa/program/Cargo.toml
patch-testing/sha/Cargo.toml
patch-testing/sha/build.rs
patch-testing/sha/program/Cargo.toml
patch-testing/sha/program/bin/sha2.rs
patch-testing/sha/src/lib.rs

* Update `rsa` tag to latest
* Test all `sha2` patched versions separately

refactor(patch-testing): `sha2`, `rsa` versions

---

patch-testing/secp256k1/build.rs
patch-testing/secp256k1/program/Cargo.toml
patch-testing/secp256k1/program/bin/recover.rs
patch-testing/secp256k1/program/bin/verify.rs
patch-testing/secp256k1/src/lib.rs

We patched `secp256k1` v0.30.0, and we need to check the patch work properly.

test: add secp256k1 v0.30.0 patch testing

---

crates/sdk/src/proof.rs

I ran into a file not found error, which was hard to read in its current form.
Give better context when file not found.

refactor: improve error handling when proof file not found

---

Cargo.lock
Cargo.toml
crates/cuda/src/lib.rs
crates/test-artifacts/programs/Cargo.lock
crates/test-artifacts/programs/fibonacci-blake3/Cargo.lock
crates/verifier/guest-verify-programs/Cargo.lock
patch-testing/Cargo.lock
patch-testing/secp256k1/program-v0.29.1/Cargo.lock
patch-testing/secp256k1/program-v0.30.0/Cargo.lock

feat: 4.2.1 release

---

Cargo.lock
crates/verifier/Cargo.toml
patch-testing/Cargo.lock

sp1-verifier publish on crates.io is failing

fix: path dependency

---

crates/sdk/src/network/client.rs
crates/sdk/src/network/prover.rs

Adds `get_balance` to the network client in the SDK.

feat(sdk): add network function for getting balance

---

crates/sdk/src/network/prove.rs

Fixing this: https://github.com/succinctlabs/sp1/actions/runs/15080038299/job/42395116604

fix(sdk): doc comment import

---

Cargo.lock
crates/build/Cargo.toml
crates/build/src/lib.rs
crates/verifier/guest-verify-programs/Cargo.lock
patch-testing/Cargo.lock

A customer asked to have access to the vkey from the script build.rs, allowing to generate a file containing the vkey as a constant.
Adding a `vkey()` fn in `sp1-build`

feat: provide an easy vay to retrieve programs vkey

---

crates/sdk/Cargo.toml
crates/sdk/src/network/builder.rs
crates/sdk/src/network/prove.rs

The signers were fetched even when TEE 2FA isn't enabled
Put TEE 2FA behind the `tee-2fa` feature.

feat: feature gate tee 2fa

---

crates/sdk/src/network/prover.rs

chore: clippy

---

crates/sdk/Cargo.toml
crates/test-artifacts/programs/Cargo.lock

Make `reserved-capacity` feature default

chore: default reserved-capacity feature

---

crates/sdk/src/network/mod.rs
crates/sdk/src/network/prover.rs

0s is not enough time for proper price discovery

chore(sdk): set default `min_auction_period` to 1s

---

crates/sdk/src/network/client.rs
crates/sdk/src/network/proto/sepolia/types.rs
crates/sdk/src/network/prove.rs
crates/sdk/src/network/prover.rs

VApp verifies that `treasury` is correct.

feat(sdk): add treasury address

---

crates/sdk/src/network/prover.rs

Exposing cancel_request in NetworkProver

fix(sdk): expose cancel_request

---

crates/prover/TRUSTED_SETUP.md
crates/sdk/src/network/tee/mod.rs

chore: revert SP1_TEE_VERSION to 1
